name: Auto Update README

on:
  schedule:
    - cron: "0 8, 16, 23 * * *"  # Runs every hour (adjust as needed)
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Python script
        run: |
          python -c "import random, string; open('README.md', 'a').write(f'\nRandom Update: {''.join(random.choices(string.ascii_letters + string.digits, k=10))}')"

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Automated update to README"
          git push
